# Use patient file and display all records

## Show number of rows and colums in your dataset

In [4]:
import pandas as pd

In [5]:
patients=pd.read_csv("patients.csv")

In [6]:
print('Patients Record as follows')
patients

Patients Record as follows

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76
...,...,...,...,...,...,...,...
995,PAT-a01bf534,Amber Vang,26,2025-12-02,2025-12-04,emergency,91
996,PAT-87fa07bd,Martha Smith,89,2025-11-18,2025-11-30,emergency,99
997,PAT-8f07e894,Jennifer James,72,2025-12-12,2025-12-21,ICU,69
998,PAT-4ae301e1,Kara Hernandez,47,2025-02-08,2025-02-20,ICU,61
999,PAT-e2ef9c5f,Lorraine Turner,64,2025-05-04,2025-05-08,general_medicine,83

In [7]:
rows, cols =patients.shape
print(f'Number of rows:{rows}')
print(f'Number of cols:{cols}')

Number of rows:1000
Number of cols:7

# Give the list of patients, whose are in ICU
## Save the file with icu_patients.csv

In [8]:
icu_patients=patients[patients['service']=='ICU']
icu_patients

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76
7,PAT-5b61868c,Ashley Waller,0,2025-05-21,2025-06-04,ICU,82
10,PAT-003ce690,Larry Dixon,29,2025-01-19,2025-01-21,ICU,60
20,PAT-5e3f8747,Elizabeth Kelley,34,2025-03-29,2025-04-12,ICU,91
24,PAT-f70aeea1,Rebecca Jackson,18,2025-02-05,2025-02-18,ICU,77
...,...,...,...,...,...,...,...
990,PAT-110d5794,Travis Hull,48,2025-11-12,2025-11-18,ICU,89
992,PAT-8700b93a,Nicholas Lawrence,9,2025-10-25,2025-11-02,ICU,92
993,PAT-e5d6a9cf,Jacob Santos,76,2025-12-27,2026-01-02,ICU,96
997,PAT-8f07e894,Jennifer James,72,2025-12-12,2025-12-21,ICU,69
998,PAT-4ae301e1,Kara Hernandez,47,2025-02-08,2025-02-20,ICU,61

In [9]:
icu_patients.to_csv('Icu_patients.csv',index=False)
print('File created')

File created